### ISSUE TITLE
Update kyverno version

### ISSUE THREAD

**Issue by shilpa-0** [gbaeke/kyverno-cli#1]
Hi,

Is this repo still being maintained? Is there a plan to update it regularly?
The latest kyverno version is 1.4.1, could you please support this? 

Thanks

**Comment by gbaeke** [comment]
I have updated v1 to use kyverno 1.4.1.

**Comment by seh** [comment]
@gbaeke, I think it's time for another release. I'm finding that the current version can't validate policies that work well with Kyverno version 1.5.

**Comment by gbaeke** [comment]
Updated to version 1.5. Let me know if this works for you...

**Comment by seh** [comment]
Thank you very much.

Do we need a new release in order for GHA to pick up the update? I'm referring to the action in my "uses" field as `gbaeke/kyverno-cli@v1`.

**Comment by gbaeke** [comment]
New runs of the v1 action should now use the updated Docker image with 1.5. I only did a simple test to check that it runs. I did not verify policies etc...

**Comment by seh** [comment]
It worked! Thank you again for your prompt update.
